(setf *print-circle* t) ;; Faction & army structs reference each other
(load "packages.lisp")
(load "oob.lisp")
(load "data.lisp")
(load "logicsetup.lisp")
(load "wtool.lisp")
(load "war.lisp")
(load "faction.lisp")
(load "worldgen.lisp")
(load "panel.lisp")
(load "tilechopper.lisp")
(load "cgen.lisp")
(load "graphicssetup.lisp")
(load "army.lisp")
